---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-pvc-nfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pg-pv-nfs
  storageClassName: ""
