---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
data:
  password: dGVzdHBhc3N3b3Jk
  redmine_password: c3VwZXJzZWNyZXRrZXk=

---
apiVersion: v1
kind: Secret
metadata:
  name: redmine-secret
type: Opaque
data:
  redmine_password: c3VwZXJzZWNyZXRrZXk=
