---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: database
  name: database
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    service: postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redmine-service
  name: redmine-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    service: redmine
