---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pv-nfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: prometheus-pv-nfs
  storageClassName: ""
